apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tea-argo
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - namespace: dev-secure
      - namespace: dev-plaintext
      - namespace: qa
  template:
    metadata:
      name: '{{namespace}}-tea-argo'
    spec:
      project: default
      source:
        repoURL: https://github.com/trevor-dolby-at-ibm-com/argocd-experiments.git
        targetRevision: HEAD
        path: kustomize-tea/envs//{{namespace}}
      destination:
        server: https://kubernetes.default.svc
        namespace: tea-argo-{{namespace}}
