apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - namespace: dev-secure
      - namespace: dev-plaintext
      - namespace: qa
  template:
    metadata:
      name: '{{cluster}}-tea-argo'
    spec:
      source:
        repoURL: https://github.com/trevor-dolby-at-ibm-com/argocd-experiments.git
        targetRevision: HEAD
        path: kustomize-tea/envs//{{cluster}}
      destination:
        namespace: tea-argo-{{namespace}}
