apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tea-argo-dev-ns

resources:
- ../../base

components:
  - ../../variants/secure

patchesStrategicMerge:
- deployment.yml
- version.yml