---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea-argo
spec:
  template:
    spec:
      containers:
      - name: tea-argo
        image: image-registry.openshift-image-registry.svc.cluster.local:5000/default/tea-tekton:latest
