apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
  - name: test-cmap
    files:
      - per-env-values.txt
    options:
      disableNameSuffixHash: true